### ISSUE TITLE
missing exr and hdr plugin and .fbx/.obj problem

### ISSUE THREAD

**Issue by leonardodentico** [ccseer/Seer-plugins#5]
Hi,thanks for the software,looks amazing,just bought the pro version.

I can't find a .json file in the imagemagick plugin folder,so I can't visualize .exr and .hdr files unfortunately...can you link me the exact file to download please?

When I open an obj file Seer crashes and I have to reopen the app,I have the 3DViwer plugin installed

thank you,
Leo

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/92343952-aa1f7c80-f0f7-11ea-98f3-26aed61e2da5.png)

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/92344221-742ec800-f0f8-11ea-90d4-192c766a3b8f.png)

**Comment by ccseer** [comment]
You mean all .obj files  or specific one .obj file?

**Comment by ccseer** [comment]
Anyway, make sure you have 2.6.0 first.


![image](https://user-images.githubusercontent.com/15963166/92344574-69c0fe00-f0f9-11ea-93c1-755dc79c6c3d.png)

**Comment by leonardodentico** [comment]
thank you for the answers

 .obj seems to work after I downloaded the latest windows upgrades and restarted!
Yes,I'm using 2.6.0

But my main problem is not with .eps.
The problem is with .hdr and .exr.
imagemick,the plugin that you linked in the software doesn't have  a .json file,so I just can't install it :( 
All the other plugins work as you can see in the image below,but I just can't get Imagemick to work...


![image](https://user-images.githubusercontent.com/70640378/92374859-a17f7400-f100-11ea-8b5d-ef1d2757c465.png)

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/92375859-4798a180-f134-11ea-87dd-0c2ce9bd483f.png)

**Comment by ccseer** [comment]
where you downloaded ImageMagick.zip ?

**Comment by leonardodentico** [comment]
https://imagemagick.org/script/download.php 

here,if you have the correct link can you please paste it here?

**Comment by ccseer** [comment]
![Uploading image.png…]()

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/92377398-ac54fb80-f136-11ea-8275-35b65d549081.png)

**Comment by leonardodentico** [comment]
ok,I found it,so it's the exr2png file,maybe it would be better to just rename it imagemagick,so the users can find it immediatly :)

Thanks again,have a nice day!

**Comment by ccseer** [comment]
Hi

I was wondering if you are willing to help me improve the translation in
Seer since I noticed that you are not an English user.

Please email me

**Comment by leonardodentico** [comment]
> Hi I was wondering if you are willing to help me improve the translation in Seer since I noticed that you are not an English user. Please email me
> […](#)

Hey! Yeah,I'm from Italy,by the way your software is pretty easy to understand in terms of language, where would you need help?

**Comment by ccseer** [comment]
Download from  https://github.com/ccseer/Seer/archive/master.zip

Then run *translation/linguist/linguist.exe*
Open *Italian.ts* in  *translation/translation_source *with linguist.exe.
It would be great if the string with  "?"  can be translated.

This is how the exe works: https://doc.qt.io/qt-5/linguist-translators.html

http://1218.io/seer/translators.html

**Comment by leonardodentico** [comment]
Hey man,check it out :)

I corrected mostly menus and stuff,as for more technical aspect I'm not 100% sure about the correct translation,so I just didn't put my hands on em

[Italian_updated.zip](https://github.com/ccseer/Seer-plugins/files/5200348/Italian_updated.zip)

**Comment by ccseer** [comment]
Wooow, thanks~

I will release this translation with Seer-2.6.1.
